### ISSUE TITLE
Kitti_tracking to Voc conversion inquiry 

### ISSUE THREAD

**Issue by benn94** [umautobots/vod-converter#10]
How does each class in `Kitti tracking` are converted to `Voc`?

 'Car', 'Van', 'Truck', 'Pedestrian', 'Person_sitting', 'Cyclist', 'Tram',  'Misc' and 'DontCare'

**Comment by krosaen** [comment]
The current implementation [specifies](https://github.com/umautobots/vod-converter/blob/master/vod_converter/voc.py#L84) that it expects to output to lower case labels which is used by [the conversion function](https://github.com/umautobots/vod-converter/blob/master/vod_converter/converter.py#L158). If the label is not found in the expected labels of the voc egestor, it will pass it through. If you wish to have the output labels in a different format, you could modify the keys in [the expected labels](https://github.com/umautobots/vod-converter/blob/master/vod_converter/voc.py#L84) dict to be whatever you choose.

**Comment by benn94** [comment]
Thank you. I am closing this issue.
