### ISSUE TITLE
Error while converting from VOC to Kitti format

### ISSUE THREAD

**Issue by sowmyadvn** [umautobots/vod-converter#12]
Hi. I am trying to convert annotation files from pascal VOC to Kitti format. When I run the command, 
`python3.6 vod_converter/main.py --from voc --from-path ~/Desktop/voc --to kitti --to-path ~/Desktop/kitti`
I get the error below:

**Failed to convert from voc to kitti: Expected subdirectory ImageSets within /Users/sowmya/Desktop/voc/VOC2012**

Could you please let me know where the conversion possibly failed? Also, it would be really helpful to specify the dependencies in ReadMe, such as PIL or jsonschema libraries. 

Thank you so much,
Sowmya

**Comment by krosaen** [comment]
hi there, this error is due to the expected layout of a VOC-like dataset, not a software dependency. 

within your VOC2012 directory you need something like `ImageSets/Main/train.txt`
