### ISSUE TITLE
KITTI annotations are corrupted after converting to VOC pascal format

### ISSUE THREAD

**Issue by yossibiton** [umautobots/vod-converter#13]
The annotations files has some mistakes after the conversion.

For example :
https://github.com/umautobots/vod-converter/blob/master/vod_converter/kitti.py#L100
in this line the bounding box right border is limited to 1023, although kitti images size is much larger than 1023.

**Comment by krosaen** [comment]
thanks for pointing this out, I'm not sure why this mistaken assumption was baked into the script. will fix asap, happy to accept a PR if you are eager.

**Comment by yossibiton** [comment]
Sorry but i don't have PR for that.
I also found other bugs with the occlusion field values which aren't
converted correctly.

Eventually I have decided to use the original annotations files of KITTI
and skip the conversion.

**Comment by krosaen** [comment]
Yeah, VOC doesn't have a notion of occlusion, so it is currently dropped (e.g any model that was originally training on pascal VOC doesn't expect occlusion fields), but I can imagine adding a custom field. Thanks again for reporting the issue.

**Comment by yossibiton** [comment]
The converted files in VOC format does have occlusion field but the values
there are wrong

**Comment by krosaen** [comment]
@yossibiton just fixed the issue, and when looking at the dataset in our viewer, I can see that things look good towards the right side of the images. It's possible that the wrong values of the don't care regions were also due to the same issue; see in this example the don't care region is now in place across the cars in the upper right

![kitti-dontcare](https://user-images.githubusercontent.com/219341/32666049-3fe3c59a-c604-11e7-8539-d43af14aae88.png)

**Comment by krosaen** [comment]
@yossibiton wait sorry you were talking about occlusion. I'll take a look at don't care values. On initial glance it looks like they aren't really being read in at all for kitti ingenstion.

**Comment by krosaen** [comment]
After looking more closely / refreshing my memory, the converter currently doesn't have a notion of occlusion in its intermediate format; when egesting KITTI it will output a value for that field but it is not meaningful. The converter currently focuses on getting labeled bounding boxes in and out of various formats, I'll consider having a notion of occlusion an enhancement todo going forward.

**Comment by krosaen** [comment]
see #14 for more notes on occlusion field
