### ISSUE TITLE
Compatibility with other python versions

### ISSUE THREAD

**Issue by nghiattran** [umautobots/vod-converter#3]
@krosaen Question: Do you intent make this repo compatible with other python versions?

If yes, I can make a PR for that.

**Comment by krosaen** [comment]
For now, no, mostly because the python3x features are handy (including format strings in python 3.6). 

Are you looking to integrate this with python2 code, or just looking for more convenient usage with an existing install?

**Comment by nghiattran** [comment]
I am looking to integrate this with python2 and I already made it compatible with python2 in my fork. So, I just wonder if you want me to make a PR.

**Comment by krosaen** [comment]
Ah I see. I think I'd prefer to keep this 3.x but thanks for the pointer. I can add a link to the README pointing to your fork so people know where to look if they need 2.x compatibility.

**Comment by krosaen** [comment]
@nghiattran I've added a link from the README to your repo for anyone who's looking for python2 support. Thanks again!
