### ISSUE TITLE
Where to find train.txt

### ISSUE THREAD

**Issue by abduallahadel** [umautobots/vod-converter#7]
Hello, 
I tried to run the converter, but it fails due to the lack of train.txt, I didn't find it on KITTiI website.

**Comment by krosaen** [comment]
train.txt is simply a list of ids. I can't remember whether they supply one as part of the datast download, but in any case, attaching one here as an example. hope this helps!
[train.txt](https://github.com/umautobots/vod-converter/files/1139276/train.txt)
