### ISSUE TITLE
I want to convert .xml file to .txt file,my order line as follows. Why mistakes occur ?

### ISSUE THREAD

**Issue by ljz1995** [umautobots/vod-converter#8]
![2017-07-03 10-57-20](https://user-images.githubusercontent.com/24621291/27776591-97eb3480-5fde-11e7-9ca1-6f6f2c9f04dc.png)

**Comment by krosaen** [comment]
it looks like the image id found in your voc xml file is non-numeric; the script currently assumes the ids for each image will be a number. Could you update your voc dataset to use numeric ids? otherwise you could probably update the script pretty easily to be more lenient for your use case.
